spring:
  application:
    name: poketmon

  mustache:
    cache: false

  datasource:
      url: jdbc:mysql://localhost:3306/your_database_name?useSSL=false&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: dongyang

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8085
